version: '3'
services:
  mysql:
    image: mysql:8
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
